export const screenName = {
  start: 'Start',
  home: 'Home',
  login: 'Login',
  register: 'Register',
  forgetPassword: 'ForgetPassword',
  transaction: 'Transaction',
  account: 'Account',
  report: 'Report',
  category: 'Category',
  interestAssets: 'Interest Assets',
  volatilityAssets: 'Volatility Assets',
  cashAssets: 'Cash Assets',
  realEstateAssets: 'Real Estate Assets',
  coin: 'Coin',
  bank: 'Bank',
  customCategory: 'Custom Category',
  assetDetail: 'Asset Detail',
};
