export const currencyList: any = {
  AUD: 'Australian Dollar',

  BTC: 'Bitcoin',

  CAD: 'Canadian Dollar',

  EUR: 'Euro',

  HKD: 'Hong Kong Dollar',

  JPY: 'Japanese Yen',
  JOD: 'Jordanian Dinar',
  KZT: 'Kazakhstani Tenge',
  KES: 'Kenyan Shilling',
  KWD: 'Kuwaiti Dinar',
  KGS: 'Kyrgystani Som',
  LAK: 'Laotian Kip',
  LVL: 'Latvian Lats',
  LBP: 'Lebanese Pound',
  LSL: 'Lesotho Loti',
  LRD: 'Liberian Dollar',
  LYD: 'Libyan Dinar',
  LTL: 'Lithuanian Litas',
  MOP: 'Macanese Pataca',
  MKD: 'Macedonian Denar',
  MGA: 'Malagasy Ariary',
  MWK: 'Malawian Kwacha',
  MYR: 'Malaysian Ringgit',
  MVR: 'Maldivian Rufiyaa',
  MRO: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MXN: 'Mexican Peso',
  MDL: 'Moldovan Leu',
  MNT: 'Mongolian Tugrik',
  MAD: 'Moroccan Dirham',
  MZM: 'Mozambican Metical',
  MMK: 'Myanmar Kyat',
  NAD: 'Namibian Dollar',
  NPR: 'Nepalese Rupee',
  ANG: 'Netherlands Antillean Guilder',
  TWD: 'New Taiwan Dollar',
  NZD: 'New Zealand Dollar',
  NIO: 'Nicaraguan CÃ³rdoba',
  NGN: 'Nigerian Naira',
  KPW: 'North Korean Won',
  NOK: 'Norwegian Krone',
  OMR: 'Omani Rial',
  PKR: 'Pakistani Rupee',
  PAB: 'Panamanian Balboa',
  PGK: 'Papua New Guinean Kina',
  PYG: 'Paraguayan Guarani',
  PEN: 'Peruvian Nuevo Sol',
  PHP: 'Philippine Peso',
  PLN: 'Polish Zloty',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SVC: 'Salvadoran ColÃ³n',
  WST: 'Samoan Tala',
  SAR: 'Saudi Riyal',
  RSD: 'Serbian Dinar',
  SCR: 'Seychellois Rupee',
  SLL: 'Sierra Leonean Leone',
  SGD: 'Singapore Dollar',
  SKK: 'Slovak Koruna',
  SBD: 'Solomon Islands Dollar',
  SOS: 'Somali Shilling',
  ZAR: 'South African Rand',
  KRW: 'South Korean Won',
  XDR: 'Special Drawing Rights',
  LKR: 'Sri Lankan Rupee',
  SHP: 'St. Helena Pound',
  SDG: 'Sudanese Pound',
  SRD: 'Surinamese Dollar',
  SZL: 'Swazi Lilangeni',
  SEK: 'Swedish Krona',
  CHF: 'Swiss Franc',
  SYP: 'Syrian Pound',
  STD: 'São Tomé and Príncipe Dobra',
  TJS: 'Tajikistani Somoni',
  TZS: 'Tanzanian Shilling',
  THB: 'Thai Baht',
  TOP: "Tongan Pa'anga",
  TTD: 'Trinidad & Tobago Dollar',
  TND: 'Tunisian Dinar',
  TRY: 'Turkish Lira',
  TMT: 'Turkmenistani Manat',
  UGX: 'Ugandan Shilling',
  UAH: 'Ukrainian Hryvnia',
  AED: 'United Arab Emirates Dirham',
  UYU: 'Uruguayan Peso',
  USD: 'US Dollar',
  UZS: 'Uzbekistan Som',
  VUV: 'Vanuatu Vatu',
  VEF: 'Venezuelan BolÃvar',
  VND: 'Vietnamese Dong',
  YER: 'Yemeni Rial',
  ZMK: 'Zambian Kwacha',
};
