import { APP_CONTENT } from 'shared/constants';

const CONTENT = APP_CONTENT.currencyList;

export const currencyList: any = {
  AUD: CONTENT.AUD,
  GBP: CONTENT.GBP,
  CAD: CONTENT.CAD,
  CNY: CONTENT.CNY,
  EUR: CONTENT.EUR,
  HKD: CONTENT.HKD,
  INR: CONTENT.INR,
  JPY: CONTENT.JPY,
  KPW: CONTENT.KPW,
  SGD: CONTENT.SGD,
  THB: CONTENT.THB,
  USD: CONTENT.USD,
  VND: CONTENT.VND,
  RUB: CONTENT.RUB,
};
